### PR TITLE
added two javascript books

### LINKED ISSUE #32: Adding new resources
Adding new links to free e-books

### PR DESCRIPTION
**Pull request by OlojaMuyiwa**
# close issue #32

<!-- Added two javascript books

Closes #32

### CODE REVIEW

**Comment by EOEboh** [comment]
@OlojaMuyiwa you seem to have some little conflicts on the PR. Can you list the full names of the books you added?

**Comment by OlojaMuyiwa** [comment]
@EOEboh i added 

Functional programming in Javascript : How to improve your Javascript program using

Javascript the definitive Guide master the world most used programming language by David flanagan

Simplifying Javascript: Writing writing modern javascript with Es5, Es6 and beyond

**Comment by OlojaMuyiwa** [comment]
i've fixed the conflict

**Comment by EOEboh** [comment]
> i've fixed the conflict

Thank you for fixing it. But the second book you listed seems to have been added before. Please kindly remove it, so I can merge your PR

**Comment by OlojaMuyiwa** [comment]
@EOEboh  done

**Review by EOEboh — APPROVED** [review]

**Comment by EOEboh** [comment]
@all-contributors please add @OlojaMuyiwa for code

**Pull request merged**
