### PR TITLE
Add workflow for pull request

### PR DESCRIPTION
**Pull request by ibrahimraimi**
Added pull request template

### CODE REVIEW

**Review by binadiegha — APPROVED** [review]
Thanks for adding this.

**Review by binadiegha — CHANGES_REQUESTED** [review]
Hey @ibrahimraimi, please add the alphabet section.

example:
```
### R
[ReactJS Book](https://goalkicker.com/ReactJSBook/)

```

**Comment by EOEboh** [comment]
@ibrahimraimi  please can you reference the `PULL_REQUEST_TEMPLATE.md` on the `CONTRIBUTING.md`? I would appreciate that.

**Comment by ibrahimraimi** [comment]
@EOEboh I just finished adding the guide for the `PULL_REQUEST_TEMPLATE.md` in `CONTRIBUTING.md`

**Pull request merged**
