### PR TITLE
Update javascript.md

### PR DESCRIPTION
**Pull request by jemmycodes**

### CODE REVIEW

**Review by binadiegha — CHANGES_REQUESTED** [review]
@jemmycodes please fix the sorting in alphabetical order:
Created a section for **E** and move **Eloquent Javascript...** up to that section:

Example: 
```
### E
- [Eloquent Jav...](link)
```
do the same for each addition

💪🏾

**Comment by EOEboh** [comment]
> @jemmycodes please fix the sorting in alphabetical order: Created a section for **E** and move **Eloquent Javascript...** up to that section:
> 
> Example:
> 
> ```
> ### E
> - [Eloquent Jav...](link)
> ```
> 
> do the same for each addition
> 
> 💪🏾

Yes please, that would be nice @jemmycodes

**Comment by EOEboh** [comment]
@jemmycodes are those google drive links public? Please ensure anyone can access them. Thanks

**Comment by jemmycodes** [comment]
>


> @jemmycodes are those google drive links public? Please ensure anyone can access them. Thanks

sure! i've given anyone with the link access to the books

**Pull request merged**
