### PR TITLE
Add new books

### PR DESCRIPTION
**Pull request by sammy-code98**
# Pull Request

## Description

Adding new books for Linux and  Git
~ create Linux and GIT folders respectively
~ add two books to each of the folders

### CODE REVIEW

**Review by Klin-Coders — COMMENTED** [review]
Thank you for your contribution
But, According to the current layout, other contributors are sorting resources alphabetically, with alphabetic headings, kindly look into adding some to yours

### G 
... rest

### P
...rest

**Review by Klin-Coders — COMMENTED** [review]
Thank you for your contribution
But, According to the current layout, other contributors are sorting resources alphabetically, with alphabetic headings, kindly look into adding some to yours

### T
... resource details

**Comment by sammy-code98** [comment]
Thank you for pointing this out chief @Klin-Coders , it totally escaped my mind.

i will fix that now

thank you

**Review by Klin-Coders — COMMENTED** [review]
LGTM

**Comment by EOEboh** [comment]
@sammy-code98  have you made the corrections?

**Comment by sammy-code98** [comment]
> @sammy-code98 have you made the corrections?

Yeah Capt.

Made them immediatly it was mentioned. @Klin-Coders  has already reviewed it

**Review by EOEboh — APPROVED** [review]

**Pull request merged**
